FROM golang:1.21 AS builder
WORKDIR $GOPATH/src/github.com/docker/helm-transform
COPY .. .
RUN go build -o /go/bin/transform

FROM scratch
COPY --from=builder /go/bin/transform /helm-transform
COPY helm-templates /templates
CMD ["/helm-transform", "helm"]