name: Transformer Images

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  transformer-image:
    strategy:
      matrix:
        target: ["transformer_all", "kubernetes_all", "helm_all"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          # driver: cloud
          # endpoint: ${{ secrets.DOCKER_BUILD_CLOUD_ENDPOINT }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker/compose-bridge-transformer
          tags: |
            type=ref,event=tag
            type=edge
          bake-target: meta-helper
      -
        name: Build and push image
        uses: docker/bake-action@v6
        id: bake
        with:
          source: .
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: ${{ matrix.target }}
          push: true
          sbom: true
          provenance: mode=max
          set: |
            *.cache-from=type=gha,scope=transformer-images
            *.cache-to=type=gha,scope=transformer-images,mode=max

